id: PEF728339
initial_creation_type: ocr
source_metadata:
  volumes:
    1b4cc8cbce0a4f769708ddfc0187eb9f:
      base_file: v070.txt
      image_group_id: I1PD95915
      title: ཐེག་པ་ཆེན་པོ་རྒྱུད་བླ་མའི་བསྟན་བཅོས་རྣམ་པར་བཤད་པ།
      total_pages: 1505
      volume_number: 70
